// Code generated by gobind. DO NOT EDIT.

// Java class libv2ray.CoreController is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/2dust/AndroidLibXrayLite
package libv2ray;

import go.Seq;

/**
 * CoreController represents a controller for managing Xray core instance lifecycle
 */
public final class CoreController implements Seq.Proxy {
	static { Libv2ray.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	/**
	 * NewCoreController initializes and returns a new CoreController instance
	Sets up the console log handler and associates it with the provided callback handler
	 */
	public CoreController(CoreCallbackHandler s) {
		this.refnum = __NewCoreController(s);
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewCoreController(CoreCallbackHandler s);
	
	CoreController(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public final native CoreCallbackHandler getCallbackHandler();
	public final native void setCallbackHandler(CoreCallbackHandler v);
	
	public final native boolean getIsRunning();
	public final native void setIsRunning(boolean v);
	
	/**
	 * MeasureDelay measures network latency to a specified URL through the current core instance
	Uses a 12-second timeout context and returns the round-trip time in milliseconds
	An error is returned if the connection fails or returns an unexpected status
	 */
	public native long measureDelay(String url) throws Exception;
	/**
	 * QueryAllOutboundTrafficStats retrieves and resets all outbound traffic counters.
	Returns a single-line text in format: tag,direction,value;tag,direction,value;
	Returns an empty string if the stats manager is not initialized or no counters exist.
	 */
	public native String queryAllOutboundTrafficStats();
	/**
	 * QueryStats retrieves and resets traffic statistics for a specific outbound tag and direction
	Returns the accumulated traffic value and resets the counter to zero
	Returns 0 if the stats manager is not initialized or the counter doesn&#39;t exist
	 */
	public native long queryStats(String tag, String direct);
	public native void registerProcessFinder(ProcessFinder finder);
	/**
	 * StartLoop initializes and starts the core processing loop
	Thread-safe method that configures and runs the Xray core with the provided configuration
	Returns immediately if the core is already running
	 */
	public native void startLoop(String configContent, int tunFd) throws Exception;
	/**
	 * StopLoop safely stops the core processing loop and releases resources
	Thread-safe method that shuts down the core instance and triggers necessary callbacks
	 */
	public native void stopLoop() throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof CoreController)) {
		    return false;
		}
		CoreController that = (CoreController)o;
		CoreCallbackHandler thisCallbackHandler = getCallbackHandler();
		CoreCallbackHandler thatCallbackHandler = that.getCallbackHandler();
		if (thisCallbackHandler == null) {
			if (thatCallbackHandler != null) {
			    return false;
			}
		} else if (!thisCallbackHandler.equals(thatCallbackHandler)) {
		    return false;
		}
		boolean thisIsRunning = getIsRunning();
		boolean thatIsRunning = that.getIsRunning();
		if (thisIsRunning != thatIsRunning) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getCallbackHandler(), getIsRunning()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("CoreController").append("{");
		b.append("CallbackHandler:").append(getCallbackHandler()).append(",");
		b.append("IsRunning:").append(getIsRunning()).append(",");
		return b.append("}").toString();
	}
}

