// Code generated by gobind. DO NOT EDIT.

// Java class libv2ray.CoreCallbackHandler is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/2dust/AndroidLibXrayLite
package libv2ray;

import go.Seq;

/**
 * CoreCallbackHandler defines interface for receiving callbacks and notifications from the core service
 */
public interface CoreCallbackHandler {
	public long onEmitStatus(long p0, String p1);
	public long shutdown();
	public long startup();
	
}

