// Code generated by gobind. DO NOT EDIT.

// Java class libv2ray.Libv2ray is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/2dust/AndroidLibXrayLite
package libv2ray;

import go.Seq;

public abstract class Libv2ray {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Libv2ray() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyCoreCallbackHandler implements Seq.Proxy, CoreCallbackHandler {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyCoreCallbackHandler(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native long onEmitStatus(long p0, String p1);
		public native long shutdown();
		public native long startup();
	}
	private static final class proxyProcessFinder implements Seq.Proxy, ProcessFinder {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyProcessFinder(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native long findProcessByConnection(String network, String srcIP, long srcPort, String destIP, long destPort);
	}
	
	
	/**
	 * CheckVersionX returns the library and Xray versions
	 */
	public static native String checkVersionX();
	/**
	 * InitCoreEnv initializes environment variables and file system handlers for the core
	It sets up asset path, certificate path, XUDP base key and customizes the file reader
	to support Android asset system
	 */
	public static native void initCoreEnv(String envPath, String key);
	/**
	 * MeasureOutboundDelay measures the outbound delay for a given configuration and URL
	 */
	public static native long measureOutboundDelay(String ConfigureFileContent, String url) throws Exception;
	/**
	 * NewCoreController initializes and returns a new CoreController instance
	Sets up the console log handler and associates it with the provided callback handler
	 */
	public static native CoreController newCoreController(CoreCallbackHandler s);
	/**
	 * ReconcileBrowserDialer updates the browser dialer address and reloads its configuration
	If the dialer address is empty, it will disable the browser dialer and close existing connections
	 */
	public static native void reconcileBrowserDialer(String dialerAddr);
}
