// Code generated by gobind. DO NOT EDIT.

// Java class libv2ray.ProcessFinder is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/2dust/AndroidLibXrayLite
package libv2ray;

import go.Seq;

/**
 * ProcessFinder is an interface for Android process finding functionality.
Apps using AndroidLibXrayLite should implement FindProcessByConnection()
and pass the implementation to RegisterProcessFinder() before starting the core.
 */
public interface ProcessFinder {
	/**
	 * FindProcessByConnection finds the UID of the process that owns the given connection.
	
	network: Protocol type: &#34;tcp&#34; or &#34;udp&#34;
	srcIP: Source IP address
	srcPort: Source port
	destIP: Destination IP address
	destPort: Destination port
	Returns the UID of the owning process, or -1 if not found.
	 */
	public long findProcessByConnection(String network, String srcIP, long srcPort, String destIP, long destPort);
	
}

